spring:
  mvc:
    servlet:
      path: /api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

scheduler:
  post-publisher:
    cron: "0 0/1 * 1/1 * ?" # every minute
    size_batch: 1
  ad-remover:
    cron: "0 0/1 * 1/1 * ?" # every minute
  moderation:
    post:
      time: 0 0 0 * * ?
      batch_size: 10_000
    comment:
      time: "0 * * * * *"
      batch_size: 100