spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 10
      enable-idempotence: true
    topic:
      post: Post

  data:
    redis:
      port: 6379
      host: localhost
      directory:
        post: Post
        infAuthor: InfAuthor
        feed: Feed_
        timestamp: :timestamp
      settings:
        ttl: 1
        maxSizeFeed: 500
      channels:
        calculations_channel:
          name: calculations_channel
        like_channel:
          name: like_view_channel
        post_view_channel:
          name: post_view_channel
        comment-event-chanel:
          name: comment_event_chanel;
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

server:
  port: 8081
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      #cron: "0 0/1 * 1/1 * ?" # every minute
      cron: "0 30 6 * * ?" # every day in 6:30
    batch-size: 2

moderationScheduler:
  cron: "0 0 0 * * *" # every day

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

s3:
  endpoint: http://127.0.0.1:9000/
  accessKey: user
  secretKey: password
  bucketName: corpbucket

commentModeratorCron: "0 0 0 * * *"

postServiceThreadPool:
  poolAmount: 4
  poolComment: 4
  poolPost: 4
  poolFeed: 4
  poolFeedAlgo: 4

servlet:
  PathV1: /api/v1

file:
  fileWithBadWords:
    path: "src/main/resources/badWords/badWords"

value:
  algoDecompose:
    firstOption: 1000
    firstOptionBatch: 100
    secondOption: 10000
    secondOptionBatch: 1000
    thirdOption: 100000
    thirdOptionBatch: 10000