spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

    kafka:
      port: 9092
      host: localhost
      group-id: account_service

    channels:
      calculations_channel:
        name: calculations_channel
      like_post_channel:
        name: like_channel

    topics:
      default-partition: 1
      default-replication: 3
      topic-settings:
        likes:
          name: likes
          partition: 1
          replication: 3
        posts:
          name: posts
          partition: 1
          replication: 3
        comments:
          name: comments
          partition: 1
          replication: 3
        post-views:
          name: posts
          partition: 1
          replication: 3

  cache:
    default-ttl: 3600
    default-max-size: 1000
    cache-settings:
      hashtag:
        name: hashtags
        max-size: 1000
      users:
        name: users
        max-size: 1000
        ttl: 3600

  servlet:
    multipart:
      max-file-size: 5MB

  profiles:
    active: test

server:
  port: 8081

logging:
  level:
    root: info

services:
  s3:
    endpoint: http://127.0.0.1:9000/
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    targetWidth: 1080
    targetHeight: 566
    maxFilesAmount: 10


post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0 0 * * *"  # Каждый день в полночь
    threads-count: 20
    max-list-size: 100
  moderator:
    path-curse-words: "src/main/resources/curse-words.txt"
    scheduler:
      cron: "0 0 * * * ?" # every midnight
    threads-count: 20
    max-list-size: 100
  user-ban:
    scheduler:
      cron: "0 0 * * * ?"
    channel:
      name: user_ban_channel
  correcter:
    scheduler:
      cron: "0 0 0 * * *"

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

async:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 100

spelling:
  url: https://speller.yandex.net/services/spellservice.json/checkText?text=
  threads: 4

moderation:
  cron: "0 0 0 * * *"  # Каждый день в полночь
  dictionary:
    filepath: "classpath:bad-words.txt"
  threads-count: 30
  batch-size: 100

api:
  path: /api/v1
