spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        user_ban_channel:
          name: user_ban

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  user_ban:
    scheduler:
      cron: "00 01 06 * * *"
  spell-corrector:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
    url: "https://speller.yandex.net/services/spellservice.json/checkText"

user-service:
  host: localhost
  port: 8080
  path: user-service
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

currency:
  api-url: "https://v6.exchangerate-api.com/v6/{key}/latest/{conversion-rate}"
  api-key: "dd32616c8ec9707b977a7895"
  conversion-rate-usd: "USD"
  fetcher:
    cron: "0 0 0 * * ?"  # Запуск каждый день в полночь
    retry:
      maxAttempts: 3     # Максимум 3 попытки
      backoff: 2000      # Интервал между попытками (в миллисекундах)

