spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel: calculations-channel
        comment_event_channel: comment-event-channel
        user_ban: user-ban
        like_channel: like-channel


  config:
    import: classpath:values/values.yaml

server:
  port: 8081

logging:
  level:
    root: info

post:

  cache:
    # SERVICE ANF SCHEDULER MUST BE EQUALS
    update: 60 # minutes
    scheduler:
      #cron: "0 0 * * * ?" #evry hour
      cron: "0/20 * * * * ?" #evry 20 sec for testing

  publisher:
    scheduler:
      #cron: "0 0/1 * 1/1 * ?" # every minute
      cron: "0/5 * * * * ?" #evry 5 sec for testing

  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

  quantity_elements: 3 #quantity element for async

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080
