spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        user_ban_channel:
          name: user_ban_channel

server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute


comment:
  moderation:
    scheduler:
      cron: "0 0 0 * * ?" # every day at midnight
    batchSize: 100
    maxThreadPoolSize: 10
    coreThreadPoolSize: 5
    queueCapacity: 100
  ban:
    scheduler:
      cron: "0 0 * * * ?" # every hour

correcter:
  scheduler:
    cron: "0 0 0 * * ?" # Every day at midnight



user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

ai:
  api:
    key: 7b59c5412dmsha6284a44d021ab9p14f51cjsn2e93aa88df77
    host: "textgears-textgears-v1.p.rapidapi.com"
    path: "/grammar"
