spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        post_comment_channel:
          name: post_comment_channel
        post_view_channel: post_view_channel
        like_topic: like_topic
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

logging:
  level:
    root: info
    faang.school.postservice: debug

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

news-feed:
  feed:
    amount: 20
    posts_size: 100
    max_retries: 5
    max_comments: 3
  heat:
    post_amount: 500
  cache:
    suffix:
      feed: feed
      post: post
      user: user

kafka:
  address: localhost:9092
  topics:
    partitions: 3
    replications: 1
    like_event: like
    comment_event: comment
    post_event: post
    post_view_event: post_view
  header_class_key: type