post:
  publisher:
    scheduler:
      batch_size: 2
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  config:
    thread-pool:
      core-pool-size: 1
      maximum-pool-size: 10
      keep-alive-time: 0
      time-unit: MILLISECONDS