spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      time-to-live: 86400
      channels:
         like_post_channel:
          name: like_channel
         comment_channel:
           name: comment_channel
      feed-cache:
        size: 500
        key-prefix: "feed:"
      post-cache:
        key-prefix: "post:"
        likes: "likes"
        comments: "comments"
        views: "view"
        comments-in-post: 3

  kafka:
    listener:
      ack-mode: manual
    bootstrap_servers: "localhost:9092"
    topic-name:
      likes: "likes"
      post-views: "post_views"
      comments: "comments"
      posts: "posts"


server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

sizeof-sublist: 100

cron-expression: 00 50 17 ? * *

like-service:
  batch-size: 100