spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        new_comment_channel:
          name: new_comment_channel

server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

user-service:
  host: localhost
  port: 8080
  requiredHeaders: x-user-id
project-service:
  host: localhost
  port: 8082
  requiredHeaders: x-user-id
payment-service:
  host: localhost
  port: 9080
  requiredHeaders: x-user-id

moderate:
  comments:
    initialDelay: 5000
    fixedDelay: 3600000

dictionary:
  offensive:
    initial: "dictionary/offensive-words.yaml"
    remote:
      url: https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/refs/heads/master
      scheduler:
        cron: "0 0 0/24 * * *" # every 24 hours
    update:
      retry:
        maxAttempts: 2
        maxDelay: 1000
services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    connectionTimeout: 50_000
    socketTimeout: 50_000

executor:
  capacity: 10
  corePoolSize: 1
  maximumPoolSize: 10
  keepAliveTime: 60
