spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  images:
    max-to-upload: 10
    max-size: 5242880
    bucket:
      name-prefix: posts/post_

client:
  s3:
    minio:
      url: http://127.0.0.1:9000
      username: user
      password: password
      bucketName: corpbucket

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

app:
  post:
    cache:
      post_id_prefix: "post:"
      number_of_top_in_cache: 10
      retryable:
        save_keys:
          max_attempts: 3
          delay: 100
          multiplier: 2
        compare_tags:
          max_attempts: 3
          delay: 50
  async-config:
    post-cache-service:
      core_pool_size: 10
      max_pool_size: 20
      queue_capacity: 1000
      thread_mane_prefix: PostCacheProcessExecutor-Async-

springdoc:
  api-docs:
    path: /api-docs
