spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  servlet:
    multipart:
      max-file-size = 5MB
      max-request-size = 5MB


  image:
    cover:
      maxHeight: 566
      maxWidth: 1080
      maxSize: 5242880

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        comment_channel:
          name: comment_channel
        user_ban_channel:
          name: user_ban_channel
        like_channel:
          name: like_channel

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group
    topics:
      post-publication: post-publication
      like-publication: like-publication
      comment-publication: comment-publication



server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
#      cron: "0 0/1 * 1/1 * ?" # every minute
      cron: "0/10 * * * * ?" # every 10 second
    ad-remover:
      scheduler:
         cron: "0 0/1 * 1/1 * ?" # every minute


schedule:
  publishing_limit: 100
  retry_limit: 3
  time_interval: 300

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

ai-spelling:
  cron: "0 0 6 * * ?" # every day at 6:00
  url: "https://bing-spell-check2.p.rapidapi.com/spellcheck"
  mode: "spell"
  contentType: "application/x-www-form-urlencoded"
  xRapidApiKey: "58a3c43c12msh2fe078f7a3f1c46p1b5471jsn5c4c9497ff76"
  xRapidApiHost: "bing-spell-check2.p.rapidapi.com"
  retry:
    maxAttempts: 10
    maxDelay: 1000

bing-thread-poll:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 100000

ad-remover:
  cron: "0 0 3 * * ?" #every day at 03:00
  batch: 100
  thread-count: 5
  retry:
    maxAttempts: 5
    maxDelay: 1000

bad-words:
  path: files/bad-words.csv

moderation-thread-pool:
  queueCapacity: 100
  maxPoolSize: 4
  corePoolSize: 4
  threadNamePrefix: "poolThread-"

moderation-properties:
  secondsBetweenModeration: 18000
  batchSize: 1000



thread-pool:
  queueCapacity: 100
  maxPoolSize: 4
  corePoolSize: 4
  threadNamePrefix: "poolThread-"

batch-size-from-like: 100

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    isMocked: false