spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      lock-registry:
        key: registry-key
        ttl-millis: 10000
        try-lock-millis: 2000
      cache:
        post:
          ttl-hours: 24
        user:
          ttl-hours: 24
        news-feed:
          ttl-hours: 24
          prefix: NewsFeed

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      group-id:
        post: post
    topic:
      post:
        published: post-published-topic

  async:
    executor:
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 500

news-feed:
  max-size: 500
  batch-size: 20

server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080
