spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        comment: comment_channel
        user_ban:
          name: user_ban_channel
      cache:
        ttl:
          user: 86400 #equals one day in seconds
          post: 86400
  mvc:
    servlet:
      path: /api/v1


multipart:
  max_video_file_size: 104857600 #100MB
  max_request_size: 524288000 #500MB
  max_image_file_size: 5242880 #5MB

server:
  port: 8085

logging:
  level:
    root: info

post:
  content_to_post:
    max_amount:
      any: 10
      video: 5
      audio: 5
      image: 10
  rule:
    unverified_posts_limit: 5
  auto_banner:
    scheduler:
      cron: "0 0 0 * * *" # every day at 00:00

publisher:
  scheduler:
    cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute


s3:
  endpoint: http://127.0.0.1:9000
  accessKey: user
  secretKey: password
  bucketName: corpbucket
  region: null
  isMocked: false

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

kafka:
  bootstrap-servers: localhost:9092
  producer:
    batch_size: 10000
  consumer:
    group-id: post_service
  topics:
    post:
      name: post_topic
    post_view:
      name: post_view_topic
    comment:
      name: comment_topic
    like:
      name: like_topic

feed:
  max_size: 500
  batch_size: 20