spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      thread-pool:
        core-pool-size: 1
        maximum-pool-size: 10
        keep-alive-time: 0
        time-unit: MILLISECONDS
      batch_size: 1000
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

comment:
  moderator:
    scheduler:
      cron: "0 0 12 * * ?" # every day 12:00
  batch:
    size: 50

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

post-correcter:
  url: "https://bing-spell-check2.p.rapidapi.com/spellcheck"
  mode: "spell"
  contentType: "application/x-www-form-urlencoded"
  xRapidApiKey: "871e222f4dmsha404f4603a4687ep188b05jsn4942910dec51"
  xRapidApiHost: "bing-spell-check2.p.rapidapi.com"
  cron: "0 0 3 * * *" # every day at 03:00
  rateLimitPerSecond: 3
