name: CI with Gradle
on:
  push:
    branches:
      - "feature-BJS2-16167"
  pull_request:
    branches:
      - "feature-BJS2-16167"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test
        run: ./gradlew test