name: ci
on:
  pull_request:
    branches:
      - kraken-master-bc3

jobs:
  start-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit-tests
        run: ./gradlew test


